networks:
  "diy_bridge":
    driver: bridge
    name: diy_bridge

services:
# 看门狗
  "watchtower":
    restart: always
    networks: [diy_bridge]
    container_name: watchtower
    image: containrrr/watchtower:latest
    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
    environment: {TZ: Asia/Shanghai, WATCHTOWER_SCHEDULE: "0 0 6 * * *"}

# OpenList
  "openlist":
    user: "0:0"
    restart: always
    ports: ["5244:5244"]
    networks: [diy_bridge]
    container_name: openlist
    environment: {TZ: Asia/Shanghai}
    image: openlistteam/openlist:latest-lite-aio
    volumes: ["./data:/overlay","./data/openlist:/opt/openlist/data"]

# Lucky
  "lucky":
    restart: always
    profiles: [disabled]
    container_name: lucky
    ports: ["16601:16601"]
    networks: [diy_bridge]
    image: gdy666/lucky:v2
    environment: {TZ: Asia/Shanghai}
    volumes: ["./data/lucky:/goodluck/data"]

# Dpanel
  "dpanel":
    restart: always
    profiles: [disabled]
    ports: ["8000:8080"]
    networks: [diy_bridge]
    container_name: dpanel
    image: dpanel/dpanel:lite
    environment: {TZ: Asia/Shanghai}
    volumes: ["./data/dpanel:/dpanel","/var/run/docker.sock:/var/run/docker.sock"]

# 1Panel
  "1panel":
    restart: always
    profiles: [disabled]
    ports: ["8001:10086"]
    networks: [diy_bridge]
    container_name: 1panel
    image: moelin/1panel:latest
    environment: {TZ: Asia/Shanghai,BASE_DIR: /opt,ENTRANCE: 1panel}
    volumes: ["./data/1panel:/opt/1panel","/var/run/docker.sock:/var/run/docker.sock"]

# 联通Token
  "token":
    profiles: [disabled]
    ports: ["8010:5702"]
    container_name: token
    networks: [diy_bridge]
    restart: unless-stopped
    image: twh808/unicom-login:latest

# 青龙面板
  "qinglong":
    profiles: [disabled]
    ports: ["8011:5700"]
    networks: [diy_bridge]
    restart: unless-stopped
    container_name: qinglong
    image: whyour/qinglong:latest
    environment: {TZ: Asia/Shanghai}
    volumes: ["./data/qinglong:/ql/data"]

# 呆呆面板
  "ddpanel":
    profiles: [disabled]
    ports: ["8012:5700"]
    networks: [diy_bridge]
    container_name: ddpanel
    restart: unless-stopped
    environment: {TZ: Asia/Shanghai}
    image: linzixuanzz/daidai-panel:latest
    volumes: ["./data/Dumb-Panel:/app/Dumb-Panel"]

# lxserver
  "lxserver":
    ports: ["8013:9527"]
    profiles: [disabled]
    networks: [diy_bridge]
    restart: unless-stopped
    container_name: lxserver
    image: ghcr.io/xcq0607/lxserver:latest
    environment: {TZ: Asia/Shanghai,FRONTEND_PASSWORD: "lxserver"}
    volumes: ["./data/lxserver/data:/server/data","./data/lxserver/logs:/server/logs"]

# AdGuardHome
  "adguardhome":
    profiles: [disabled]
    networks: [diy_bridge]
    restart: unless-stopped
    container_name: adguardhome
    environment: {TZ: Asia/Shanghai}
    image: adguard/adguardhome:latest
    ports: ["8014:3000","153:53","853:853"]
    volumes: ["./data/adguard/work:/opt/adguardhome/work","./data/adguard/conf:/opt/adguardhome/conf"]

# LibreTV
  "libretv":
    ports: ["8015:8080"]
    profiles: [disabled]
    networks: [diy_bridge]
    restart: unless-stopped
    container_name: libretv
    image: ghcr.io/librespark/libretv:latest
    environment: {TZ: "Asia/Shanghai",PASSWORD: "libretv",DEFAULT_SUBSCRIPTIONS: '["https://raw.githubusercontent.com/Forget-Dust/Grocery/main/Docker/Files/libretv.json"]'}

# Apt-Linux
  "aptlinux":
    profiles: [disabled]
    networks: [diy_bridge]
    restart: unless-stopped
    container_name: aptlinux
    image: library/debian:12
    environment: {TZ: Asia/Shanghai}
    entrypoint: ["/bin/bash", "-c", "set -e;M=/var/cache/.mirror_done;if [ ! -f \"$$M\" ];then (command -v curl &>/dev/null || (apt-get update && apt-get install -y curl));bash <(curl -sfSL https://gitee.com/SuperManito/LinuxMirrors/raw/main/ChangeMirrors.sh) --source mirrors.tencent.com --protocol http --backup true --upgrade-software true --clean-cache true --ignore-backup-tips;echo `(date)`>\"$$M\";fi;exec tail -F /dev/null"]

# Yum-Linux
  "yumlinux":
    profiles: [disabled]
    networks: [diy_bridge]
    restart: unless-stopped
    container_name: yumlinux
    image: library/rockylinux:9
    environment: {TZ: Asia/Shanghai}
    entrypoint: ["/bin/bash", "-c", "set -e;M=/var/cache/.mirror_done;if [ ! -f \"$$M\" ];then (command -v curl &>/dev/null || yum install -y curl);bash <(curl -sfSL https://gitee.com/SuperManito/LinuxMirrors/raw/main/ChangeMirrors.sh) --source mirrors.tencent.com --protocol http --use-intranet-source false --install-epel true --backup true --upgrade-software true --clean-cache true --ignore-backup-tips;echo `(date)`>\"$$M\";fi;exec tail -F /dev/null"]
